export interface PhoneDialOption {
  dial: string;
  label: string;
  iso2: string;
}

/** Common international dial codes for phone signup (E.164 prefix). `iso2` selects SVG flag (ISO 3166-1 alpha-2). */
export const PHONE_DIAL_CODES: PhoneDialOption[] = [
  { dial: "+98", label: "IR", iso2: "IR" },
  { dial: "+966", label: "SA", iso2: "SA" },
  { dial: "+971", label: "AE", iso2: "AE" },
  { dial: "+964", label: "IQ", iso2: "IQ" },
  { dial: "+965", label: "KW", iso2: "KW" },
  { dial: "+973", label: "BH", iso2: "BH" },
  { dial: "+968", label: "OM", iso2: "OM" },
  { dial: "+974", label: "QA", iso2: "QA" },
  { dial: "+972", label: "IL", iso2: "IL" },
  { dial: "+962", label: "JO", iso2: "JO" },
  { dial: "+961", label: "LB", iso2: "LB" },
  { dial: "+90", label: "TR", iso2: "TR" },
  { dial: "+93", label: "AF", iso2: "AF" },
  { dial: "+1", label: "US/CA", iso2: "US" },
  { dial: "+44", label: "UK", iso2: "GB" },
  { dial: "+49", label: "DE", iso2: "DE" },
  { dial: "+33", label: "FR", iso2: "FR" },
  { dial: "+39", label: "IT", iso2: "IT" },
  { dial: "+34", label: "ES", iso2: "ES" },
  { dial: "+31", label: "NL", iso2: "NL" },
  { dial: "+32", label: "BE", iso2: "BE" },
  { dial: "+41", label: "CH", iso2: "CH" },
  { dial: "+43", label: "AT", iso2: "AT" },
  { dial: "+45", label: "DK", iso2: "DK" },
  { dial: "+46", label: "SE", iso2: "SE" },
  { dial: "+47", label: "NO", iso2: "NO" },
  { dial: "+358", label: "FI", iso2: "FI" },
  { dial: "+353", label: "IE", iso2: "IE" },
  { dial: "+351", label: "PT", iso2: "PT" },
  { dial: "+48", label: "PL", iso2: "PL" },
  { dial: "+7", label: "RU/KZ", iso2: "RU" },
  { dial: "+380", label: "UA", iso2: "UA" },
  { dial: "+86", label: "CN", iso2: "CN" },
  { dial: "+81", label: "JP", iso2: "JP" },
  { dial: "+82", label: "KR", iso2: "KR" },
  { dial: "+886", label: "TW", iso2: "TW" },
  { dial: "+852", label: "HK", iso2: "HK" },
  { dial: "+65", label: "SG", iso2: "SG" },
  { dial: "+60", label: "MY", iso2: "MY" },
  { dial: "+66", label: "TH", iso2: "TH" },
  { dial: "+84", label: "VN", iso2: "VN" },
  { dial: "+62", label: "ID", iso2: "ID" },
  { dial: "+63", label: "PH", iso2: "PH" },
  { dial: "+91", label: "IN", iso2: "IN" },
  { dial: "+92", label: "PK", iso2: "PK" },
  { dial: "+880", label: "BD", iso2: "BD" },
  { dial: "+94", label: "LK", iso2: "LK" },
  { dial: "+998", label: "UZ", iso2: "UZ" },
  { dial: "+994", label: "AZ", iso2: "AZ" },
  { dial: "+20", label: "EG", iso2: "EG" },
  { dial: "+218", label: "LY", iso2: "LY" },
  { dial: "+213", label: "DZ", iso2: "DZ" },
  { dial: "+27", label: "ZA", iso2: "ZA" },
  { dial: "+234", label: "NG", iso2: "NG" },
  { dial: "+254", label: "KE", iso2: "KE" },
  { dial: "+61", label: "AU", iso2: "AU" },
  { dial: "+64", label: "NZ", iso2: "NZ" },
  { dial: "+54", label: "AR", iso2: "AR" },
  { dial: "+55", label: "BR", iso2: "BR" },
  { dial: "+52", label: "MX", iso2: "MX" },
  { dial: "+51", label: "PE", iso2: "PE" },
  { dial: "+56", label: "CL", iso2: "CL" },
  { dial: "+57", label: "CO", iso2: "CO" },
  { dial: "+36", label: "HU", iso2: "HU" },
  { dial: "+30", label: "GR", iso2: "GR" },
  { dial: "+355", label: "AL", iso2: "AL" },
  { dial: "+385", label: "HR", iso2: "HR" },
  { dial: "+40", label: "RO", iso2: "RO" },
  { dial: "+359", label: "BG", iso2: "BG" },
  { dial: "+970", label: "PS", iso2: "PS" },
  { dial: "+967", label: "YE", iso2: "YE" },
];

export function defaultDialForLocale(locale: string | undefined): string {
  return locale === "fa" ? "+98" : "+1";
}
